# Generated by Django 4.2.5 on 2023-09-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('title', models.TextField()),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255, verbose_name='Association')),
                ('geeks_field', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-data_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Media_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('title', models.TextField(verbose_name='Title')),
                ('data_time_create', models.DateTimeField(auto_now_add=True)),
                ('data_time_update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, verbose_name='Association')),
                ('geeks_field', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-data_time_update', 'title', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.comments')),
            ],
            bases=('main.comments',),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.media_models', verbose_name='Model_ID'),
        ),
    ]
